<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShipmentSeeder extends Seeder
{
    public function run(): void
    {
        $shipments = [
            [
                'tracking_number' => 'OD-99283-AUTO',
                'reference_number' => 'REF-2026-99283',
                'quote_id' => 1,
                'customer_name' => 'John Smith',
                'customer_email' => 'john.smith@example.com',
                'customer_phone' => '+234-123-456-7890',
                'vehicle_make' => 'BMW',
                'vehicle_model' => 'X5',
                'vehicle_year' => '2022',
                'vehicle_vin' => 'WBAJA5C50LWX12345',
                'vehicle_description' => 'Premium SUV with panoramic sunroof and leather interior',
                'origin_port' => 'Bremerhaven',
                'origin_country' => 'Germany',
                'destination_port' => 'Lagos',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'grimaldi',
                'vessel_name' => 'Atlantic Mariner V24',
                'container_number' => 'MSCU 123456 7',
                'booking_number' => 'BKG-2026-88921',
                'status' => 'shipping',
                'progress_percentage' => 45,
                'shipping_date' => now()->subDays(10),
                'departure_date' => now()->subDays(8),
                'estimated_arrival_date' => now()->addDays(12),
                'total_cost' => 28500.00,
                'notes' => 'Customer requested enclosed container shipping',
                'admin_notes' => 'High-value shipment - priority handling',
                'is_active' => true,
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(2)
            ],
            [
                'tracking_number' => 'OD-99401-AUTO',
                'reference_number' => 'REF-2026-99401',
                'quote_id' => 2,
                'customer_name' => 'Elena Rodriguez',
                'customer_email' => 'elena.r@example.com',
                'customer_phone' => '+234-987-654-3210',
                'vehicle_make' => 'Tesla',
                'vehicle_model' => 'Model Y',
                'vehicle_year' => '2023',
                'vehicle_vin' => '5YJ3E1EA8PF987654',
                'vehicle_description' => 'Electric SUV, Long Range variant, white exterior',
                'origin_port' => 'Los Angeles',
                'origin_country' => 'USA',
                'destination_port' => 'Abuja',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'sallaum',
                'vessel_name' => 'Pacific Explorer',
                'container_number' => 'HLCU 789012 3',
                'booking_number' => 'BKG-2026-90342',
                'status' => 'in_transit',
                'progress_percentage' => 65,
                'shipping_date' => now()->subDays(18),
                'departure_date' => now()->subDays(15),
                'estimated_arrival_date' => now()->addDays(5),
                'total_cost' => 42000.00,
                'notes' => 'Battery transport documentation required',
                'admin_notes' => 'Hazmat clearance approved',
                'is_active' => true,
                'created_at' => now()->subDays(22),
                'updated_at' => now()->subDays(1)
            ],
            [
                'tracking_number' => 'OD-88120-AUTO',
                'reference_number' => 'REF-2026-88120',
                'quote_id' => 3,
                'customer_name' => 'Marcus Thorne',
                'customer_email' => 'marcus.t@example.com',
                'customer_phone' => '+234-555-111-2222',
                'vehicle_make' => 'Ford',
                'vehicle_model' => 'F-150',
                'vehicle_year' => '2021',
                'vehicle_vin' => '1FTFW1E82MKF56789',
                'vehicle_description' => 'Full-size pickup truck, FX4 Off-Road package',
                'origin_port' => 'Houston',
                'origin_country' => 'USA',
                'destination_port' => 'Port Harcourt',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'grimaldi',
                'vessel_name' => 'Atlantic Mariner V24',
                'container_number' => 'MSCU 456789 0',
                'booking_number' => 'BKG-2026-77651',
                'status' => 'customs',
                'progress_percentage' => 80,
                'shipping_date' => now()->subDays(30),
                'departure_date' => now()->subDays(25),
                'estimated_arrival_date' => now()->subDays(5),
                'actual_arrival_date' => now()->subDays(5),
                'total_cost' => 18500.00,
                'notes' => 'RoRo shipping preferred for pickup',
                'admin_notes' => 'Customs processing - ETA 3 days',
                'is_active' => true,
                'created_at' => now()->subDays(35),
                'updated_at' => now()->subDays(2)
            ],
            [
                'tracking_number' => 'OD-77231-AUTO',
                'reference_number' => 'REF-2026-77231',
                'quote_id' => 4,
                'customer_name' => 'David Chen',
                'customer_email' => 'david.chen@example.com',
                'customer_phone' => '+234-444-333-2222',
                'vehicle_make' => 'Porsche',
                'vehicle_model' => '911',
                'vehicle_year' => '2024',
                'vehicle_vin' => 'WP0AA2A90PS123456',
                'vehicle_description' => 'Sports car, Carrera S, black with red interior',
                'origin_port' => 'Hamburg',
                'origin_country' => 'Germany',
                'destination_port' => 'Lagos',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'other',
                'vessel_name' => 'Ocean Spirit',
                'container_number' => 'HLCU 345678 9',
                'booking_number' => 'BKG-2026-66120',
                'status' => 'delivered',
                'progress_percentage' => 100,
                'auction_date' => now()->subDays(60),
                'shipping_date' => now()->subDays(45),
                'departure_date' => now()->subDays(40),
                'estimated_arrival_date' => now()->subDays(15),
                'actual_arrival_date' => now()->subDays(15),
                'delivery_date' => now()->subDays(10),
                'total_cost' => 95000.00,
                'notes' => 'Enclosed container, climate controlled',
                'admin_notes' => 'Delivered successfully - customer satisfied',
                'is_active' => true,
                'created_at' => now()->subDays(65),
                'updated_at' => now()->subDays(10)
            ],
            [
                'tracking_number' => 'OD-12399-AUTO',
                'reference_number' => 'REF-2026-12399',
                'quote_id' => 5,
                'customer_name' => 'Sarah Jenkins',
                'customer_email' => 'sarah.j@example.com',
                'customer_phone' => '+234-777-888-9999',
                'vehicle_make' => 'Toyota',
                'vehicle_model' => 'RAV4',
                'vehicle_year' => '2019',
                'vehicle_vin' => 'JTMBFREV0HJ123789',
                'vehicle_description' => 'Compact SUV, XLE trim, AWD',
                'origin_port' => 'Tokyo',
                'origin_country' => 'Japan',
                'destination_port' => 'Abuja',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'sallaum',
                'vessel_name' => 'Pacific Explorer',
                'container_number' => 'MSCU 890123 4',
                'booking_number' => 'BKG-2026-55430',
                'status' => 'documentation',
                'progress_percentage' => 25,
                'auction_date' => now()->subDays(5),
                'total_cost' => 15500.00,
                'notes' => 'Import permit application in progress',
                'admin_notes' => 'Waiting for SONCAP certificate',
                'is_active' => true,
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(1)
            ],
            [
                'tracking_number' => 'OD-00212-AUTO',
                'reference_number' => 'REF-2026-00212',
                'quote_id' => 6,
                'customer_name' => 'Liam Wilson',
                'customer_email' => 'liam.w@example.com',
                'customer_phone' => '+234-222-333-4444',
                'vehicle_make' => 'Audi',
                'vehicle_model' => 'Q7',
                'vehicle_year' => '2022',
                'vehicle_vin' => 'WA1LAAF71ND123456',
                'vehicle_description' => 'Luxury SUV, Prestige trim, quattro AWD',
                'origin_port' => 'Rotterdam',
                'origin_country' => 'Netherlands',
                'destination_port' => 'Lagos',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'grimaldi',
                'vessel_name' => 'Atlantic Mariner V24',
                'container_number' => 'HLCU 567890 1',
                'booking_number' => 'BKG-2026-44321',
                'status' => 'pending',
                'progress_percentage' => 5,
                'total_cost' => 38000.00,
                'notes' => 'Quote approved, awaiting deposit payment',
                'admin_notes' => 'Deposit reminder sent',
                'is_active' => true,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(3)
            ],
            [
                'tracking_number' => 'OD-55789-AUTO',
                'reference_number' => 'REF-2026-55789',
                'quote_id' => null,
                'customer_name' => 'Amara Okafor',
                'customer_email' => 'amara.o@example.com',
                'customer_phone' => '+234-333-444-5555',
                'vehicle_make' => 'Mercedes-Benz',
                'vehicle_model' => 'GLE 450',
                'vehicle_year' => '2023',
                'vehicle_vin' => 'W1N4M4HB7NW123456',
                'vehicle_description' => 'Premium SUV, AMG Line package',
                'origin_port' => 'Hamburg',
                'origin_country' => 'Germany',
                'destination_port' => 'Lagos',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'sallaum',
                'vessel_name' => 'Pacific Explorer',
                'container_number' => 'MSCU 234567 8',
                'booking_number' => 'BKG-2026-33210',
                'status' => 'auction_won',
                'progress_percentage' => 15,
                'auction_date' => now()->subDays(3),
                'total_cost' => 52000.00,
                'notes' => 'Auction won on Copart, payment processing',
                'admin_notes' => 'Wire transfer initiated',
                'is_active' => true,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(1)
            ],
            [
                'tracking_number' => 'OD-33445-AUTO',
                'reference_number' => 'REF-2026-33445',
                'quote_id' => null,
                'customer_name' => 'Chidi Nwosu',
                'customer_email' => 'chidi.n@example.com',
                'customer_phone' => '+234-666-777-8888',
                'vehicle_make' => 'Lexus',
                'vehicle_model' => 'RX 350',
                'vehicle_year' => '2021',
                'vehicle_vin' => '2T2BZMCA7HC123456',
                'vehicle_description' => 'Luxury crossover, F Sport package',
                'origin_port' => 'Houston',
                'origin_country' => 'USA',
                'destination_port' => 'Port Harcourt',
                'destination_country' => 'Nigeria',
                'shipping_provider' => 'grimaldi',
                'vessel_name' => 'Ocean Spirit',
                'container_number' => 'HLCU 678901 2',
                'booking_number' => 'BKG-2026-22109',
                'status' => 'cancelled',
                'progress_percentage' => 0,
                'total_cost' => 0.00,
                'notes' => 'Order cancelled by customer',
                'admin_notes' => 'Refund processed, account closed',
                'is_active' => false,
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(25)
            ]
        ];

        foreach ($shipments as $shipment) {
            DB::table('shipments')->insert($shipment);
        }

        // Seed Shipment Updates
        $updates = [
            ['shipment_id' => 1, 'status' => 'pending', 'location' => 'Los Angeles, USA', 'description' => 'Quote approved, preparing auction', 'update_date' => now()->subDays(14)],
            ['shipment_id' => 1, 'status' => 'auction_won', 'location' => 'Los Angeles, USA', 'description' => 'Auction won on Copart, vehicle secured', 'update_date' => now()->subDays(12)],
            ['shipment_id' => 1, 'status' => 'shipping', 'location' => 'Bremerhaven, Germany', 'description' => 'Vehicle loaded, container sealed', 'update_date' => now()->subDays(10)],
            ['shipment_id' => 1, 'status' => 'in_transit', 'location' => 'Atlantic Ocean', 'description' => 'Vessel departed on schedule', 'update_date' => now()->subDays(8)],
            ['shipment_id' => 2, 'status' => 'pending', 'location' => 'California, USA', 'description' => 'Quote approved', 'update_date' => now()->subDays(20)],
            ['shipment_id' => 2, 'status' => 'auction_won', 'location' => 'San Diego, USA', 'description' => 'Auction won, vehicle at yard', 'update_date' => now()->subDays(18)],
            ['shipment_id' => 2, 'status' => 'shipping', 'location' => 'Los Angeles Port', 'description' => 'Loaded onto Pacific Explorer', 'update_date' => now()->subDays(15)],
            ['shipment_id' => 2, 'status' => 'in_transit', 'location' => 'Pacific Ocean', 'description' => 'On schedule, ETA 5 days', 'update_date' => now()->subDays(10)],
            ['shipment_id' => 3, 'status' => 'pending', 'location' => 'Texas, USA', 'description' => 'Quote converted to shipment', 'update_date' => now()->subDays(32)],
            ['shipment_id' => 3, 'status' => 'auction_won', 'location' => 'Houston, USA', 'description' => 'Vehicle purchased at auction', 'update_date' => now()->subDays(30)],
            ['shipment_id' => 3, 'status' => 'shipping', 'location' => 'Houston Port', 'description' => 'RoRo loading completed', 'update_date' => now()->subDays(28)],
            ['shipment_id' => 3, 'status' => 'in_transit', 'location' => 'Gulf of Mexico', 'description' => 'Atlantic Mariner en route', 'update_date' => now()->subDays(20)],
            ['shipment_id' => 3, 'status' => 'customs', 'location' => 'Port Harcourt, Nigeria', 'description' => 'Arrived at port, customs processing', 'update_date' => now()->subDays(5)],
            ['shipment_id' => 4, 'status' => 'pending', 'location' => 'Stuttgart, Germany', 'description' => 'Order initiated by customer', 'update_date' => now()->subDays(60)],
            ['shipment_id' => 4, 'status' => 'auction_won', 'location' => 'Munich, Germany', 'description' => 'Porsche secured at dealer auction', 'update_date' => now()->subDays(55)],
            ['shipment_id' => 4, 'status' => 'shipping', 'location' => 'Hamburg Port', 'description' => 'Enclosed container loaded', 'update_date' => now()->subDays(45)],
            ['shipment_id' => 4, 'status' => 'in_transit', 'location' => 'North Sea', 'description' => 'Ocean Spirit departed Hamburg', 'update_date' => now()->subDays(40)],
            ['shipment_id' => 4, 'status' => 'customs', 'location' => 'Lagos Port', 'description' => 'Customs clearance completed', 'update_date' => now()->subDays(12)],
            ['shipment_id' => 4, 'status' => 'delivered', 'location' => 'Lagos, Nigeria', 'description' => 'Delivered to customer residence', 'update_date' => now()->subDays(10)]
        ];

        foreach ($updates as $update) {
            DB::table('shipment_updates')->insert($update);
        }
    }
}
