/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.jsx',
    ],
    theme: {
        extend: {
            colors: {
                'primary-fixed-dim': '#c0c1ff',
                'on-tertiary-container': '#787cea',
                'on-surface-variant': '#c7c5d3',
                'surface-container-highest': '#333535',
                'on-secondary-container': '#4b1b00',
                'surface-dim': '#121414',
                'surface-variant': '#333535',
                'primary-fixed': '#e1e0ff',
                'surface-container': '#1e2020',
                'surface': '#121414',
                'on-primary': '#21247b',
                'tertiary-container': '#06007a',
                'on-tertiary-fixed-variant': '#3538a3',
                'tertiary': '#c0c1ff',
                'error-container': '#93000a',
                'background': '#121414',
                'surface-container-lowest': '#0c0f0f',
                'on-primary-container': '#7b7fd8',
                'on-secondary-fixed': '#341100',
                'inverse-primary': '#5155ab',
                'on-background': '#e2e2e2',
                'on-surface': '#e2e2e2',
                'outline-variant': '#464651',
                'secondary-container': '#ea6b1b',
                'on-tertiary': '#1c1c8d',
                'tertiary-fixed': '#e1e0ff',
                'on-secondary': '#552000',
                'error': '#ffb4ab',
                'secondary': '#ffb692',
                'inverse-on-surface': '#2f3131',
                'surface-bright': '#37393a',
                'primary': '#c0c1ff',
                'primary-container': '#0d0d6b',
                'secondary-fixed-dim': '#ffb692',
                'on-primary-fixed': '#060467',
                'secondary-fixed': '#ffdbcb',
                'surface-tint': '#c0c1ff',
                'on-error': '#690005',
                'surface-container-low': '#1a1c1c',
                'surface-container-high': '#282a2b',
                'on-secondary-fixed-variant': '#793100',
                'on-error-container': '#ffdad6',
                'on-primary-fixed-variant': '#393d92',
                'inverse-surface': '#e2e2e2',
                'tertiary-fixed-dim': '#c0c1ff',
                'on-tertiary-fixed': '#05006d',
                'outline': '#918f9d'
            },
            borderRadius: {
                'DEFAULT': '0.125rem',
                'lg': '0.25rem',
                'xl': '0.5rem',
                'full': '0.75rem'
            },
            spacing: {
                'md': '24px',
                'xl': '80px',
                'xs': '4px',
                'sm': '12px',
                'base': '8px',
                'lg': '48px',
                'container-max': '1280px',
                'gutter': '24px'
            },
            fontFamily: {
                'title-md': ['IBM Plex Sans'],
                'caption': ['Inter'],
                'body-lg': ['Inter'],
                'headline-lg': ['IBM Plex Sans'],
                'label-md': ['IBM Plex Sans'],
                'headline-lg-mobile': ['IBM Plex Sans'],
                'body-md': ['Inter'],
                'display-lg': ['IBM Plex Sans']
            },
            fontSize: {
                'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }]
            }
        }
    },
    plugins: [],
};
